### ISSUE TITLE
Systemd Unit Error (code=exited, status=210/CHROOT) at ExecStop

### ISSUE THREAD

**Issue by DanHCraft** [agowa338/MinecraftSystemdUnit#14]
I have the following problem:
https://gist.github.com/DanHCraft/3a6f238843307ff078fc3d54db889ee7

And if I google it I get no sollution for specificaly this problem.
I have taken a look in the other issues and here are the other information you want:
### which java
/usr/bin/java
### java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
### which screen
/usr/bin/screen
###  screen -version
Screen version 4.05.00 (GNU) 10-Dec-16
### tree -L 1 /home/<user>/Forge/DKKCP (thats the path in my way)
/home/<user>/Forge/DKKCP/
|-- 1.12.2.json
|-- OpenComputersMod-1.7.5.192-lua53-native.64.so
|-- backups
|-- banned-ips.json
|-- banned-players.json
|-- config
|-- crafttweaker.log
|-- crash-reports
|-- eula.txt
|-- forge-1.12.2-14.23.5.2854.jar
|-- journeymap
|-- libraries
|-- local
|-- logs
|-- minecraft_server.1.12.2.jar
|-- mods
|-- ops.json
|-- options.txt
|-- patchouli_books
|-- scripts
|-- server.properties
|-- settings.sh
|-- start
|-- survival
|-- survival-20200505-060202.zip
|-- tailslibrary.json
|-- usercache.json
|-- usernamecache.json
`-- whitelist.json

**Comment by TheSageMarmot** [comment]
On ExecStart try changing the screen start options to -DmS instead of -dmS

From the man page:
-d|-D [pid.tty.host]
does not start screen, but detaches the elsewhere running screen session. It has the same effect as typing "C-a d" from screen's controlling terminal. -D is the equivalent to the power detach key. If no session can be detached, this option is ignored. In combination with the -r/-R option more powerful effects can be achieved...

(Sorry, if you received this twice. I realized I replied on the wrong page.)

**Comment by agowa** [comment]
Also you shouldn't put your minecraft instance below of /home/.
The option `ProtectHome=true` will prevent all processes started through this unit from accessing `/home`, the directory will look empty.

I'd recommend using the default `WorkingDirectory=/opt/minecraft/%i` instead.

Actually I've never tried a working directory below /home in combination with "ProtectHome", if it works I'd consider it to be a bug, as "ProtectHome" should prevent access.

**Comment by agowa** [comment]
No response for 28 days.
